### PR TITLE
Improve latexmk build process, add minted and biblatex examples, add helper scripts

### PR DESCRIPTION
**Pull request by elcorto**
* Add additional extensions to `.latexmkrc`. Remove other settings from `.latexmkrc` that are default. Set `bibtex_use`.
* Use `latexmk` in the Makefile.
* Add minted code example in `slides.tex` .
* Add biblatex usage example in `slides.tex` .
* Add helper scripts to set up this repo as template in an already existing talk repo.
  * `link-theme.sh`
  * `init-theme-submodule.sh`
  * Add corresponding README section.

### CODE REVIEW

**Comment by Markus-Goetz** [comment]
I am new to latexmk. How does it ensure that xelatex is used? Line 9 through defining what xelatex is?

**Comment by elcorto** [comment]
Yes, `xelatex` is defined to be used in the `$pdflatex` variable in `.latexmkrc` which ~is~ was already done in this repo's main branch version of `.latexmkrc` before this PR.

This PR will make `latexmk` a hard requirement for people using the `Makefile`. However, since the README suggests a full TeX distro install, that tool is most certainly available. Also note that the current `Makefile` doesn't run bibtex/biber. I added a biblatex example to `slides.tex` and `latexmk` will take care of that automatically.

**Comment by Markus-Goetz** [comment]
Thanks for the explanation. Would you consider the branch to be ready for review?

**Comment by elcorto** [comment]
Yes, no more commits planned.

**Review by Markus-Goetz — APPROVED** [review]

**Comment by Markus-Goetz** [comment]
Thank you for the contribution

**Comment by elcorto** [comment]
Thanks!

**Pull request merged**
